# railway.toml - Railway configuration file

[build]
builder = "NIXPACKS"
buildCommand = "npm run build"
startCommand = "npm start"

[deploy]
numReplicas = 1
region = "auto"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[env]
NODE_ENV = "production"
PORT = "$PORT"  # Railway will provide this automatically